### ISSUE TITLE
Unsolved Failing Tests

### ISSUE THREAD

**Issue by kliu513** [Lind-Project/lind_project#121]
To be able to run all the test cases without manually handling anything, I tried to add some features to `suite.sh`:
1. Since `forkexecv.c` executes `hello.nexe`, I tried to compile `hello.c` in `suite.sh` with `x86_64-nacl-gcc-4.4.3 hello.c -o test_out/hello -std=gnu99` before compiling any other test.
2. Since `mmaptest.c` opens` nondet.txt`, I tried to copy and move `nondet.txt` to the `test_out` file folder, where all the test cases are located, with `cp nondet.txt test_out`.
3. Since `serverclient.c` needs to be compiled with the `-lpthread` flag, I tried to compile every test with this flag in `suite.sh` with     `x86_64-nacl-gcc-4.4.3 $var -o test_out/$varnexe -std=gnu99 -lpthread` and `gcc $var -o test_out/$varnonexe -lpthread`.

All of the new features described above fail to work.

**Comment by rennergade** [comment]
Template.c is also giving extraneous output that I don't understand currently in Lind. The ordering shouldn't matter but why is it printing so much?

**Comment by kliu513** [comment]
The `segfault.c` test is also having weird behavior within Lind.

**Comment by kliu513** [comment]
`mprotect.c` is having the same problem as `mmaptest.c`: the file to be opened during the program has to be moved to the Lind file system beforehand.

**Comment by rennergade** [comment]
forkandopen.c also depends on a file so we have to update that as well

**Comment by kliu513** [comment]
> forkandopen.c also depends on a file so we have to update that as well

I do not think `forkandopen.c` depends on a file? The program actually creates `foo.txt` instead of opening it.

**Comment by rennergade** [comment]
Forkexecv and forkandopen technically need getcwd implemented for us to easily have tests for them.

**Comment by rennergade** [comment]
mprotec.c is failing because we don't have "/dev/zero" implemented in Lind

**Comment by rennergade** [comment]
mmaptest is also a path thing that getcwd would alleviate.

**Comment by kapkic** [comment]
Update: I've tried mmaptest with getcwd implemented. The underlying issue is even if the tests are being run at `/automated_tests/`, getcwd returns `/`. As a workaround, I have edited suite.sh to copy a `testfile.txt` at `/` in lindfs, . This also solves filetest.c and filetest1000.c, alongisde mmaptest.

**Comment by kapkic** [comment]
Implemented with #119 .
