### ISSUE TITLE
CWD

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#125]
getcwd is curiously not implemented. It doesn't appear in SafePOSIX.

It is hinted at in NaCl with a NaClSysGetcwd function, but it actually is never intercepted! 

Either way this should be routed through glibc and not go through nacl_syscall_common, like the other get functions "getuid" etc. This will trivially in SafePOSIX print the currentworkingdirectory dictionary.

We should also be able to modify safeposix to use CWD so it doesn't require us to specify root directory when running things (right now we have to do `lind /program.nexe` instead of `lind program.nexe`) It would make a few things easier to have this change.

**Comment by rennergade** [comment]
@youngfalcon I believe you were working on this before we migrated to RustPOSIX. 

IIRC we'll need this to get one of the main apps working? It also would be useful for getting a few of the tests working. Can you implement this after/during your work patching in `lstat`?

**Comment by youngfalcon** [comment]
Yes, we need this working. I would be happy to work on this.

**Comment by youngfalcon** [comment]
This issue was fixed with the recent PR's.
