### ISSUE TITLE
IOCTL

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#129]
ioctl() is unimplemented but seems to be needed by both postgres and nginx.

This seems to be a bit tricky since it's used in a case by case basis and is further defined by driver header files, but we should be able to fake it for our purposes.

First steps should be to look at what nginx and postgres are doing with ioctl() natively to see what we need to emulate.

@JustinCappos is there anything we should keep in mind here? Interested in hearing any top level comments.

**Comment by JustinCappos** [comment]
I would minimize what you implement.  Just do exactly what you need for
the programs you are running.

**Comment by youngfalcon** [comment]
nginx uses the FIONBIO command of ioctl. Information about this command:

`#include <sys/types.h>`
`#include <sys/ioctl.h>`
`#include <sys/socket.h>`
`#include <if.h>`

`int ioctl(int s, unsigned long cmd, void *data);`

FIONBIO
controls non-blocking I/O for socket descriptor `s`, and data points to an integer. If `*data` is `0`, `ioctl` clears non-blocking I/O. If `*data` is not `0`, `s` is set for non-blocking I/O. Calls that cannot complete immediately return a `-1` with `errno` set to `EWOULDBLOCK`.
