### ISSUE TITLE
safeposix mmap bug

### ISSUE THREAD

**Issue by jesings** [Lind-Project/lind_project#134]
Currently, the file descriptor that we pass to mmap in safeposix is the system file descriptor for the file. This means that the checks we do against the safeposix file descriptor table are incorrect and will always fail (certain internal mmaps seem to use an alternate route which is why this bug wasn't detected earlier). However, getting a non-system file descriptor for these calls would make finding the right file descriptor to mmap difficult, and we could not get that from within repy's emulated file object. The short-term fix for this will probably involve sending both a system and a safeposix file descriptor,

**Comment by rennergade** [comment]
Solved with recent PR
