### ISSUE TITLE
Lstat()

### ISSUE THREAD

**Issue by kliu513** [Lind-Project/lind_project#138]
In the `stat.c` test, it is `lstat()` instead of `stat()` that is being tested and reported "not implemented." With the new changes made to the `stat()` interface, the test now works perfectly with `stat()` in place of `lstat()`. However, `lstat()` seems to be properly defined and hooked in `glibc`, and is basically implemented in the same way with `stat()` in `NaCl`. The reason why it fails in the test is unknown.

**Comment by rennergade** [comment]
Great, lets spend some time tracking lstat then. It would be good to see some of the errors involved. Run it in verbose mode/track it with gdb.

**Comment by kliu513** [comment]
The solution turns out to be simple. `Lstat(int fd, ...) `and `stat(char* path, ...)` take in different first args although they work in basically the same way. Whoever created `stat.c` obviously messed up with this and had the file path passed to `lstat()` directly. Hence Lind was searching for a function defined as `lstat(char* path, ...)` and of course found nothing. `Lstat()` itself works fine in Lind, and a simple fix to the original test would be to open the file(s) beforehand and pass its fd to `lstat()`.
