### ISSUE TITLE
Chdir - Postgres Bug ( No such file or directory)

### ISSUE THREAD

**Issue by youngfalcon** [Lind-Project/lind_project#141]
For some reason, `chdir` fails when running Postgresql with the given error:

`could not change directory to "": No such file or directory`

This normally happens for both .`/initdb` and `./postgres` executables.

After a manual override to the empty string to change it to the root at the repy level, we still get:

`could not change directory to "/": No such file or directory`

while running `./initdb`. 

` ./postgres` also returns an error but it is no longer printed to stdout after the change.

Our individual test attempts using chdir seem to work correctly - which makes this situation hard to examine.

The development of syscalls needed for Postgres is currently on getcwd_ioctl in Lind_Glibc and nacl_repy. Any relevant tests can be run after switching to this branch in these projects and using the branch develop for all other projects.

**Comment by rennergade** [comment]
I don't believe this is a bug anymore and was fixed by implementing gethostname()
