### ISSUE TITLE
Unify RPC/Eliminate "lind_syscall" pathway

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#143]
We want to get rid of the [lind_syscall](https://github.com/Lind-Project/native_client/blob/lind/src/trusted/service_runtime/lind_syscalls.c) RPC pathway so we're only doing RPC through the "[lind_platform](https://github.com/Lind-Project/native_client/blob/lind/src/shared/platform/lind_platform.c)" interface.

@youngfalcon did some initial work on this for us, which is much appreciated, but we need to finish the job. He very forunately gave us some docs with this [wiki](https://github.com/Lind-Project/lind_project/wiki/Moving-system-calls-from-lind_syscall-path-to-NaClSyscall-path) and the screenshots below of git diffs for changing an example syscall.

[gethostname_glibc_changes.pdf](https://github.com/Lind-Project/lind_project/files/6620541/gethostname_glibc_changes.pdf)
[gethostname_native_client_changes.pdf](https://github.com/Lind-Project/lind_project/files/6620542/gethostname_native_client_changes.pdf)

**Comment by rennergade** [comment]
@kapkic Can you create a list here in this issue of which calls this has been completed for and which are left?

**Comment by kapkic** [comment]
I've compared _elf/Versions_, _call.c_ files in _sysdeps/nacl_, and the code in _irt_syscalls.c_. These calls either haven't been completed, or still call `<call>_lind` functions:

- lind_accept;
- lind_access;
- lind_bind;
- lind_connect;
- lind_fcntl_get;
- lind_fcntl_set;
- lind_getifaddrs;
- lind_getpeername;
- lind_getsockopt;
- lind_listen;
- lind_noop;
- lind_poll;
- lind_select;
- lind_setsockopt;
- lind_socketpair;
- lind_strace;
- __nacl_irt_accept;
- __nacl_irt_bind;
- __nacl_irt_connect;
- __nacl_irt_epoll_create;
- __nacl_irt_epoll_ctl;
- __nacl_irt_epoll_wait;
- __nacl_irt_getpeername;
- __nacl_irt_getsockname;
- __nacl_irt_getsockopt;
- __nacl_irt_listen;
- __nacl_irt_pipe2;
- __nacl_irt_poll;
- __nacl_irt_recvmsg;
- __nacl_irt_select;
- __nacl_irt_sendmsg;
- __nacl_irt_socketpair;

These five calls are tagged as nacl_irt in _elf/Versions_, and have `not_implemented` value in _irt_syscalls.c_:

- __nacl_irt_epoll_create1;
- __nacl_irt_epoll_pwait;
- __nacl_irt_getcwd;
- __nacl_irt_ppoll;
- __nacl_irt_pselect;

**Comment by rennergade** [comment]
We're done!!
