### ISSUE TITLE
Run Individual Tests/Debug Test Cases

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#150]
Now that we have Lind 2.0 up and running we need to stress test it. Let's run each of the tests in tests/test_cases as a prelim and debug any problems we find in them.

@kapkic can you make a list in this issue with all the tests in that repo so we can divide it up like we did with the RPC?

**Comment by kapkic** [comment]
#188 finalizes the remaining test cases into the test suite.
