### ISSUE TITLE
Update Docs/Wiki

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#152]
We need to update all the docs for the new Lind version. We have a bunch of docs in the safeposix-rust repo that we can link to as well.

**Comment by kapkic** [comment]
Docs/Wiki candidates are posted here for reviewing: https://drive.google.com/drive/folders/1yKlXoBCuCdFUL5PhbmlNVmWaUt9I4ckf?usp=sharing

**Comment by rennergade** [comment]
This has been done. Thanks @kapkic !
