### ISSUE TITLE
Test Debug - gethostname.c

### ISSUE THREAD

**Issue by kapkic** [Lind-Project/lind_project#157]
per #150.
Gethostname returns a SOH character instead of the hostname.

**Local run:**
```
[1:0 0:46] 06:01:28 Mon Oct 18 [lind@7dc564333349: +1] ~/lind_project/tests/test_cases
@(1:46) $ ./gethostname
Hostname: 7dc564333349
```

**Lind run:**
```
@(1:29) $ lind /lind/gethostname.nexe
executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /lind/gethostname.nexe]
[2555,4129261568:05:53:44.842140] BYPASSING ALL ACL CHECKS
Error in syscall: access - ENOENT: path does not refer to an existing file
Hostname:  _(SOH character)_
```

Full verbose output (-vvvv) can be found at:
[gethostname-verbose.txt](https://github.com/Lind-Project/lind_project/files/7366928/gethostname-verbose.txt)

**Comment by youngfalcon** [comment]
This is working with the safeposix/networking branch (https://github.com/Lind-Project/safeposix-rust/tree/networking). Closing.
