### ISSUE TITLE
Run extra Python modules

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#182]
Right now Python compiles and runs, but we don't have the CPython built extension modules (ie. collections). Let's figure out how to compile/load/use these.

**Comment by kapkic** [comment]
Good news: We're able to build libpython2.7.so! 
Several changes on ./bootstrap_nacl:
```
...
export CFLAGS='-g -e -fPIC -fno-pie -DPY_FORMAT_LONG_LONG="ll" -std=c99'
export CXXFLAGS='-g -fPIC -fno-pie'
...
./configure --host=x86_64-nacl --enable-shared "$@"
```

At this point, we need to successfully cross compile python binaries; which is going to be a bit tricky. Building python 2.7.2 natively and using it to compile _could_ help.

**Comment by rennergade** [comment]
I spent some time banging my head last night on this and finally got some modules to compile. Here are the steps:

1. Make build directories

mkdir build
mkdir build/lib


2. Compile object

x86_64-nacl-gcc -DPY_FORMAT_LONG_LONG=ll -std=c99 -fPIC -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -DNDEBUG -I. -IInclude -I./Include -c Modules/(filename).c -o build/(filename).o


3. Link to shared object
x86_64-nacl-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -std=c99 build/(filename).o  -L. -lpython2.7 -o build/lib/(filename-final).so


4. Copy library .so's to Lind (lib-dynload)

**Comment by kapkic** [comment]
We are able to compile rather complicated modules like zlib, _io and _hashlib at this point.
To automate the building process, I've added several scripts in #199.

**Comment by rennergade** [comment]
These compile and are scripted now! Closed.
