### ISSUE TITLE
Reconfigure/Optimize Metadata Scheme

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#184]
Right now our metadata persistence scheme can make programs incredibly slow. This happens most when we are writing to a file, as each increase in file length creates a need to update the metadata (in case of a crash). The current way we're doing it more or less is the same as it was in Repy SafePOSIX.

I'm opening up this issue to start discussion on how to overhaul this. Some questions:

1. Can we speedup the actual persistence method from our current one?
2. Possibly by splitting up metadata and only updating per file?
3. Do we have to update metadata on every write? Is there another scheme where we can handle crashes w/o doing this?
4. Do we have to handle crash inconsistencies at all?

Requesting feedback with any additional questions or answers.

**Comment by JustinCappos** [comment]
Question 4 is really the most important one.  I'll assume for a moment we want to have this happen.

If so, then likely the best thing to do would be to use a log structured filesystem (LFS) approach to writing metadata.  This means we would append changes to the metadata to a log where we only write to blocks at the end.  (You can read a lot of papers on this if you aren't familiar.)  

This should have very fast write access, but will be slower at startup.  However, we are likely doing startup asynchronously, so that cost should not really matter.

As for Question 4, we should discuss in a meeting, but my thinking is that yes we would need this for a system people would use in production.

**Comment by rennergade** [comment]
Thanks for the suggestion Justin. I think that may work well.

We'll talk about this tonight so that we hopefully have a plan that I can implement over the next few days.

I started to put this document together to layout ideas.
[Metadata RFC](https://docs.google.com/document/d/1UAZSHQiEK_IVI2JXoHM8BjjWSUYt0CL-x5NeRJF5TgY/edit#heading=h.umuadhfevul)

**Comment by rennergade** [comment]
I have an implementation working for this that reduces the overhead on a 1GB dd from > 1000x to 5x.

I'm currently close to switching that version from json to bincode which will hopefully reduce that further.

**Comment by rennergade** [comment]
Switching to cbor has decreased that overhead from 5x to 1.2x. Almost there! 

Going to profile a little to see if I can squeeze more out of this.

**Comment by rennergade** [comment]
I got it working with mmap but it actually increased the overhead. [It looks like](https://raw.githubusercontent.com/Lind-Project/lind_project/rust-graphs/graphs/dd-cbor-mmap.svg) its because I have to call truncate over and over to make sure the log isnt filled with junk.

I'm currently trying to keep count of the number of bytes written at the beginning of the log so that we don't have to call truncate at all. The FlameGraph suggests if we can do that the performance gains will be pretty substantial.

**Comment by rennergade** [comment]
Got it working!

[Here's a flamegraph for serializing with cbor and logging to a mapfile.](https://raw.githubusercontent.com/Lind-Project/lind_project/rust-graphs/graphs/dd-cbor-mmap%2Bcount.svg)

The test I've been using is
```dd if=testfile.txt of=testfile2.txt bs=1024``` where testfile is 1GB and testfile2 is a new file.

Stats:
Native: 3.5 secs
Lind w/ CBOR serialization and logging (no mapfile): 4.2 seconds
Lind w/ CBOR serialization and logging (mapfile): 3 seconds

We're now outpacing native by 15%! Awesome.

I'm going to clean this up for a merge and get data on varying blocksize. I also anticipate more gains here (and with the pipetests) when @TristanB22 finishes the conversion to dashmaps.

**Comment by rennergade** [comment]
Closed with recent PR.
