### ISSUE TITLE
Run Flask Application

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#185]
It would be great if we could run a Flask application through Python to handle our lamp stack. Flask is a common web-framework, which handles WSGI through [Werkzeug](https://github.com/pallets/werkzeug/tree/main/src/werkzeug). We'll need this to interface with nginx.

There seems to be a lot of dependencies, but seemingly from python based libraries that won't need extra compilation.

An exception is how we'll want to interface with postgres, [psycopg2](https://github.com/psycopg/psycopg2), which uses the libpq library and needs to be compiled. Once we get the standard CPython modules compiled it's worth trying to compile this as well. You can get the NaCl compiled libpq library from compiling postgres.

**Comment by kapkic** [comment]
After a while of debugging and solving issues, we got Flask running!
```
@(1:2844) $ lind /bin/bash /pyscr.sh

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash /pyscr.sh]
[23214,1520510976:07:16:24.642293] BYPASSING ALL ACL CHECKS
 * Serving Flask app "hello" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:80/ (Press CTRL+C to quit)
        127.0.0.1 - - [23/Feb/2022 17:16:38] "HEAD / HTTP/1.1" 200 -
```

This is the curl output. 
```
`@(1:4267) $ curl -I -L index.html 127.0.0.1
curl: (6) Could not resolve host: index.html
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 26
Server: Werkzeug/1.0.1 Python/2.7.2
Date: Wed, 23 Feb 2022 17:16:38 GMT`
```

**Comment by rennergade** [comment]
WOW. This is amazing!

**Comment by rennergade** [comment]
This can be closed now. We do need to run flask with psycopg2 but that will happen once we get postgres running.
