### ISSUE TITLE
Local Sockets as Pipes

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#186]
We've been successful at increasing IPC performance via pipes (and aim to do better through some mutex optimizations). On the other hand, things in the LAMP stack do IPC via sockets. WSGI uses network sockets locally, and libpq/postgres use local unix domain sockets.

We should be able to model local socket connections in RustPOSIX as a set of two pipes, one in each direction. We should be able to keep track of if a socket is A) created via NaCl/RustPOSIX and B) uses localhost. If so, we should direct RustPOSIX to use these pipes instead of actual sockets.

**Comment by rennergade** [comment]
I spent some time between writing various things last week to work on this and now have a minimal version that compiles, now needs to be debugged.

From @Devansh-Patel work getting the LAMP stack up natively it seems like we can set up gunicorn/wsgi to use domain sockets so I think we won't have to do anything for the "local ip sockets" I reference above.

**Comment by rennergade** [comment]
As of now I have the main implementation working and passing tests in safeposix/full Lind. Still need to test corner cases and auxiliary system calls that may interact with UD sockets.

**Comment by JustinCappos** [comment]
Okay, great!

**Comment by rennergade** [comment]
This branch has been sitting stagnant for awile unmerged while we were waiting to sort out other socket things in RustPOSIX. I think we're ready to try to bring this into the code base.

@TristanB22 can you attempt to reconcile the "domsocks-pipes" branch of rustposix with develop?

**Comment by rennergade** [comment]
@TristanB22 has mostly reconciled these branches but it still needs to be debugged and tested. @justyoyo123 is going to take over from here.

**Comment by rennergade** [comment]
This works now as of the mega-merge. Thank you to everyone who helped here including @TristanB22 @justyoyo123 @yizhuoliang !
