### ISSUE TITLE
Implement mmap

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#20]
We'll need to implement this in SafePOSIX to get to the goal of a fully userspace implementation. This may be done alongside  #18 but I believe that issue isn't blocking.

There is a Python version of `mmap` [here](https://docs.python.org/2/library/mmap.html) that should be useful.

Proposed steps
- Get memory location in NaCl and check bounds
- Pass ptr to Repy, use python mmap to map fd to memory location
- We'll need to get the actual fd (not SafePOSIX) using the fileobj
- Need to find a way to set memory location with Python's mmap ([perhaps using ctypes?](https://stackoverflow.com/questions/10364032/how-to-change-the-value-stored-in-memory-address) )
- For now, we'll let flags fall through to the kernel.

**Comment by jesings** [comment]
About that python mmap implementation, first of all it's in a library which is a no-go for RePy, second of all it seems to be a very thin wrapper around the mmap syscall such that I'm not sure it would add security over just doing it in C. I looked into it a little bit [here](https://github.com/python/cpython/blob/master/Modules/mmapmodule.c) if you want.

**Comment by JustinCappos** [comment]
We may add an API to Repy for Lind that takes a filelikeobject from Repy,
the relevant flags, etc. and does mmap.  This will either need to call
native code from your C routine or use the Python mmap library.

The reason to move this all to repy is that it simplifies the file
descriptor tracking, etc. immensely...

**Comment by rennergade** [comment]
per Slack discussion, @jesings is going to examine how this works with Repy and I will hook in the NaCl side.

**Comment by jesings** [comment]
I would just like to clarify that this will not require any of the security concerns of the rest of safeposix, rather it will just potentially check that the arguments are of correct form and call the python mmap. Is this correct?

**Comment by jesings** [comment]
In addition do you have any input on how to call mmap from within repy if direct importation of libraries is not an option?

**Comment by rennergade** [comment]
I think that [this repyportability file](https://github.com/Lind-Project/nacl_repy/blob/master/portability/repyportability.py) was used to port outside libraries? But I'm not exactly sure, perhaps @JustinCappos can shed some light here.

**Comment by JustinCappos** [comment]
This is used to let Repy code (like a repy library) being called from
Python.  It's probably not that relevant for Lind.

**Comment by rennergade** [comment]
@jesings you can either quickly monkeypatch mmap in [here](https://github.com/Lind-Project/nacl_repy/blob/eaf48b510d98e83ff0292ee24b963b59a5dc7b79/repy/repy.py#L181) which should be good to start. The more accepted way to interface is [here](https://github.com/Lind-Project/nacl_repy/blob/eaf48b510d98e83ff0292ee24b963b59a5dc7b79/repy/namespace.py#L612) if you want to try that out.

**Comment by jesings** [comment]
From my research into how to implement this, I understand now how to get a C pointer from the python mmap object (although how that will interface with NaCl I'm not sure. The problem is use of this pointer renders the mmap object unusable and unclosable (without errors), even if the pointer is deleted. This [stackoverflow post](https://stackoverflow.com/questions/53339931/properly-discarding-ctypes-pointers-to-mmap-memory-in-python) lays it out. In addition, I'm not sure whether or not we need to store a reference to mmap to save it from the garbage collector and/or to recover from the invalid state we set it to by using the c pointer? If so, I was thinking that it could be metadata on that file descriptor, and have a custom destructor if we needed it.

**Comment by JustinCappos** [comment]
My reading of the issue and thinking about why Python would do this leads
me to believe that they don't want data structures that are needed by the
garbage collector to be mmaped away.  Since we're only mapping memory that
will not contain Python objects (it is in the guest cages), this shouldn't
be a problem for us.

**Comment by rennergade** [comment]
Something I'm also noticing is that we're going to need to specify a starting address to mmap (the parameter `void *addr` from the [manpage](http://man7.org/linux/man-pages/man2/mmap.2.html)). The plan is to get a safe starting address from NaCl and send it to SafePOSIX to map there.

It seems though you can specify this starting address for the system call, the Python implementation hides that ability from us? We may need to hack into that.

**Comment by JustinCappos** [comment]
If the python interface isn't quite what you need, there is always more directly making calls to the OS interface with ctypes.  We use that a fair amount in the repy sandbox already...

**Comment by jesings** [comment]
This should be complete now, with the additions of these commits to [lind glibc](https://github.com/Lind-Project/Lind-GlibC/commit/847dbc9dd094633d81b790eef24fb633715fec69), [lind project](https://github.com/Lind-Project/lind_project/commit/aa007b5bb2034a8c7232d0057c53e4bfc660a7fa), [nacl_repy](https://github.com/Lind-Project/nacl_repy/commit/5cf7f453b7ed9417fda924dd1fd3f815b7a7e446), and  [native_client](https://github.com/Lind-Project/native_client/commit/e01eddf847bf08e03d2d656e030fdc101b396d2f).
These changes have (at least with the insufficient amount of testing I have put them through) not caused any issues of things working differently from how they did previously.
Mmap works by intercepting only the last part of the NaCl mmap syscall, the part where it actually calls the posix mmap, and routing that through safeposix before calling the patched in libc mmap wrapper using ctypes. 
Munmap in NaCl is performed by performing a lot of checking before finally mmapping a region of length 0 over the old mmapped region. This final mmap call is now performed in safeposix, where it calls out to the same patched in libc mmap wrapper using ctypes.
One issue that I encountered was that the cageid could not reach the function where NaCl calls mmap when MAP_ANONYMOUS was specified, (and therefore the cageid could not reach repy) so I set all of those to have a cageid of 0 for the time being. This is not the intended behavior for this syscall from a  lind point of view, but this was the case before we added in mmap. I talked with @rennergade about this and he told me that we'd likely fold the function where NaCl calls mmap into one of its calling functions which has access to the cageid to rectify this behavior.
Please let me know if you have any remaining questions about this issue!

**Comment by rennergade** [comment]
This is really awesome. Let's make sure we comb through and add appropriate safety checks, or at least ensure they are there.

**Comment by rennergade** [comment]
Nice, this ones finally done!
