### ISSUE TITLE
Files get merged when copying to lindfs

### ISSUE THREAD

**Issue by kapkic** [Lind-Project/lind_project#203]
When copying multiple files to lind, sometimes they get merged with another file, which can cause issues.
This does not happen all the time, but it's _rather_ reproducible.

Steps to reproduce:

- run `lindfs format` to reset it
- `make install` to install the default packages back
- copy your files (you can use the load_python etc scripts for this)

Upon running a file with dependencies (i.e. python scripts), you'll get broken file errors, it's hard to find the exact file without running scripts as there's a lot of files to check and this does not happen on all the files.

The issue usually goes away after running the same _lindfs cp_ command again.

Sample file:
```
@(1:127) $ cat pyscr.sh
#Points out the envars and runs python in lind.
export PYTHONHOME="/usr"
export PYTHONPATH="/usr/local/lib/python2.7/:/usr/local/lib/python2.7/lib-dynload/:/usr/local/lib/python2.7/site-packages/"
/bin/python "/hello.py" #you can rename, edit and copy the files hello.py and pythonscript.sh to make changes.
```
Lindfs output: 

[Lindout.txt](https://github.com/Lind-Project/lind_project/files/8006562/Lindout.txt)

On this case, it merges with flaskvenv/flaskenv/lib/python2.7/site-packages/werkzeug/_reloader.py file.

```
@(1:3278) $ grep -rn 'loaded files from modules, all files in folders of already loaded modules'
lind/lindenv/fs/linddata.2991:16:    loaded files from modules, all files in folders of already loaded modules
lind/lindenv/fs/linddata.6247:16:    loaded files from modules, all files in folders of already loaded modules
grep: lind/lindenv/fs/linddata.6257: binary file matches
site-packages/werkzeug/_reloader.py:16:    loaded files from modules, all files in folders of already loaded modules
flaskvenv/flaskenv/lib/python2.7/site-packages/werkzeug/_reloader.py:16:    loaded files from modules, all files in folders of already loaded modules
```

**Comment by jesings** [comment]
In the files that you are copying--are there symlinks? Any other kind of special files? Have you seen this doing something other than copying a directory recursively?

**Comment by kapkic** [comment]
Yes, there are symlinks. Makes sense as we don't see this when doing makelind. The other files are _mostly_ .so's, .py's and .c's. 
This also happens when copying a single file (pyscr.sh) after a bulk copy.

**Comment by jesings** [comment]
I believe this gets fixed by Lind-Project/safeposix-rust#105, but have not tested it.

**Comment by rennergade** [comment]
@jesings @kapkic did we confirm this is fixed?

**Comment by kapkic** [comment]
I will look into this tonight.

**Comment by kapkic** [comment]
Tried it a couple times with the reproduce steps. Seems to be fixed!
