### ISSUE TITLE
Python unimplemented functions.

### ISSUE THREAD

**Issue by kapkic** [Lind-Project/lind_project#205]
_Posting here since this might be a larger-glibc related issue._

When we build python/Modules/_socket.so, it segfaults at these functions:

```
socket.gethostbyname()
socket.gethostbyaddr()
socket.getaddrinfo()
```
The _socket.so has the functions linked to glibc:
```
nm -g _socket.so | grep get
0000000000006ee0 T fake_getaddrinfo -> this works, socket.getaddrinfo('127.0.0.1', 80)
                 U gethostbyaddr@@GLIBC_2.2.5
                 U gethostbyname@@GLIBC_2.2.5
                 U gethostname@@GLIBC_2.2.5 --> this works, socket.gethostname()
                 ...
```
I don't think we have the functions implemented in glibc, 

Info:
hello.py:
```
import socket
local_ip = socket.gethostbyname('Lind') #socket.gethostname() returns 'Lind', made it explicit for clarity.
```

Lind output:
```
@(1:498) $ lind /bin/bash /pyscr2.sh

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash /pyscr2.sh]
[190409,3038820352:08:58:40.742553] BYPASSING ALL ACL CHECKS

** Signal 11 from trusted code: pc=560c6abb4e71
```
Verbose file: [Verbose-Lind.txt](https://github.com/Lind-Project/lind_project/files/8008709/Verbose-Lind.txt)

@jesings @rennergade

**Comment by jesings** [comment]
@rennergade this seems like another one of those preprocessor defines that is not there for something within nacl's glibc.

**Comment by rennergade** [comment]
as far as I can tell these _are_ defined in glibc, so something else is weird. They're most likely there but broken?

```@(1:2353) $ nm -g libc.so.990e7c45 | grep gethostbyname
000000000016c660 T gethostbyname
000000000016c9e0 T gethostbyname2
000000000016cd60 T gethostbyname2_r@@GLIBC_2.2.5
000000000016d2e0 T gethostbyname_r@@GLIBC_2.2.5```

```@(1:2352) $ nm -g libc.so.990e7c45 | grep gethostbyaddr
000000000016bca0 T gethostbyaddr
000000000016c000 T gethostbyaddr_r@@GLIBC_2.2.5
```

**Comment by jesings** [comment]
Ok so I looked into this a fair bit today, and here's the state of that. gethostbyname definitely does exist in C, but it is currently broken. There was an address translation issue in the poll system call (the fds array wasn't getting its user address changed to a sys address in NaCl) that I fixed in lind-project/native_client#90, which was almost definitely causing your seg fault. However, there is a remaining issue, that being that it now hangs on that poll call (which is being called from res_send.c in lind_glibc), by never exiting the rustposix section [i.e. nothing polled ever seems ready]). Looking into this further it seems the fd set on the pollstruct is 0 which is definitely incorrect because we should in no circumstance be trying to write to stdin... hopefully this gets us near the right track with this stuff!

**Comment by jesings** [comment]
Additionally there was an error in how rustposix laid out the poll struct, which is fixed Lind-Project/safeposix-rust#107, and now we no longer even hang we just get returned a NULL on something that should succeed. Definitely progress but we're not there quite yet.

**Comment by kapkic** [comment]
I think we can close this issue now as all the functions are working.

pytest.py
```
import socket
print(socket.gethostbyname("google.com"))
print(socket.gethostbyaddr("google.com"))
print(socket.getaddrinfo("google.com",80))
```

Native output:
```
$ python pytest.py
142.251.40.174
('lga25s81-in-f14.1e100.net', [], ['142.251.40.174'])
[(2, 1, 6, '', ('142.251.40.174', 80)), (2, 2, 17, '', ('142.251.40.174', 80)), (2, 3, 0, '', ('142.251.40.174', 80)), (10, 1, 6, '', ('2607:f8b0:4006:821::200e', 80, 0, 0)), (10, 2, 17, '', ('2607:f8b0:4006:821::200e', 80, 0, 0)), (10, 3, 0, '', ('2607:f8b0:4006:821::200e', 80, 0, 0))]
```

Lind output:
```
executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash /pyscr.sh]
[23592,1312610304:07:31:25.728843] BYPASSING ALL ACL CHECKS
142.251.40.174
('lga25s81-in-f14.1e100.net', [], ['142.251.40.174'])
[(2, 2, 17, '', ('142.251.40.174', 80))]
```

**Comment by rennergade** [comment]
Closed with recent PRs.
