### ISSUE TITLE
dup

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#21]
We'll need the dup family of syscalls to work for the Bash/LAMP milestone. There's some implementations in place but it needs to be futher investigated. These need to all move to the SafePOSIX side and work with all fds.

**Comment by rennergade** [comment]
Looking into this a bit, I believe that [though dup calls have been created in SafePOSIX](https://github.com/Lind-Project/nacl_repy/blob/eaf48b510d98e83ff0292ee24b963b59a5dc7b79/seattlelib/lind/lind_fs_calls.py#L1723) , they aren't called via RPC anymore and its handled internally? I don't think that should happen.

The IRT in glibc suggests that dup/dup2/dup3 are directing towards the implementations in [nacl_syscall_common.c](https://github.com/Lind-Project/native_client/blob/9436cf1a0f2ae9d4ce65acc43658385e50bbb660/src/trusted/service_runtime/nacl_syscall_common.c#L459). These don't seem to make calls to the RPC stubs in lind_platform.

A lot of these calls are routed through [NaClSysLindSyscall](https://github.com/Lind-Project/native_client/blob/9436cf1a0f2ae9d4ce65acc43658385e50bbb660/src/trusted/service_runtime/lind_syscalls.c#L777) but my inclination that the dup family is not doing this.

It would be good to:
1. Put some print statements in the SafePOSIX dup implementations, run some tests using dup/dup2/dup3, and see if those are reached.
2. Run lind through gdb with those tests and see where the those syscalls lead internally.

**Comment by rennergade** [comment]
It seems like we're having some problems with fds in #33 and it may be because of `dup` (or may be an issue elsewhere that dup is uncovering).

Neel, it would be great to get some simpler tests where we use dup/dup2 as well as scenarios where we fork and use these.

**Comment by rennergade** [comment]
I'm running this simple test of fork+dup and getting an error, this would seem to be the same problem bash is facing.

Test Program:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

int main(int argc, char *argv[])
{
    int fd = open("write.txt", O_RDWR | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
    pid_t child = fork();

    if(child == 0)
    {
        int backup = dup(STDOUT_FILENO);   // make backup of stdout
        dup2(fd,STDOUT_FILENO);// use dup2 so child printf() goes into file, not screen
        printf("I'm the child\n");
        fflush(stdout);
        dup2(backup,STDOUT_FILENO);
    }
    else
    {
        printf("I'm the parent\n");
    }

    printf("all done\n");
    close(fd);
    return 0;
}

```

Error Message:
```
executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /forkdup.nexe]
Lind v1.0-rc2
Opening file system...
done.
[545,2487169664:13:51:38.086628] BYPASSING ALL ACL CHECKS
Persisting metadata: ...
Traceback (most recent call last):
  File "../repy/lind_server.py", line 9554, in finalize
    persist_metadata(DEFAULT_METADATA_FILENAME)
  File "../repy/lind_server.py", line 2415, in persist_metadata
    metadatafo = openfile(metadatafilename,True)
  File "../repy/namespace.py", line 1257, in wrapped_function
    retval = func_to_call(*args_to_use)
  File "../repy/emulfile.py", line 183, in emulated_open
    return emulated_file(filename, create)
  File "../repy/emulfile.py", line 273, in __init__
    raise FileInUseError('Cannot open file "'+filename+'" because it is already open!')
exception_hierarchy.FileInUseError: Cannot open file "lind.metadata" because it is already open!
I'm the parent
all done
```

**Comment by JustinCappos** [comment]
It looks to me like it is trying to re-instantiate the safePOSIX file
system again after forking.  It should only do this once, regardless of the
number of cages that use that file system.

Do you want to put in a print statement there to see if I'm right?

**Comment by JustinCappos** [comment]
To revise what I'm saying slightly.  I think both cages may be trying to
persist the file system concurrently and there isn't locking around this
function.

**Comment by rennergade** [comment]
Oh that's interesting. I'm going to comb through this at a finer level tomorrow. Hopefully will flesh this out.

**Comment by rennergade** [comment]
So I think the above error was a red herring. I traced the `dup` calls, and they're not even going into SafePOSIX (which was my initial thought) instead being handled by NaCl internally. 

I think the error above was from some sort of FS corruption, I haven't seen it since I reformatted my lindfs, but I'll be on the watch for it.

**Comment by rennergade** [comment]
I'm going to move dup to SafePOSIX either way but am spending some time digging through the NaCl side to make sure the descriptors work properly.

It seems like the above program doesn't actually fail until it tries to close the 
I'm still running some tests on this NaCl version of dup just to make sure my methods for nacl_desc handling are correct. The strange part here is that its actually failing at the last close of the initial fd from open, and not in the actual dup calls.

Error message: `[5525,4137346816:09:34:25.482951] Fatal error in file src/shared/platform/posix/nacl_fast_mutex.c, line 23: !(0 == pthread_mutex_lock(&flp->mu))`

I'm not exactly sure I'm using `NaClDescRef` and `NaClDescUnref` correctly, maybe this is the issue?

Either way switching this to `dup` to SafePOSIX should be fairly straightforward. I'll get that done early next week and see if these problems persist.

**Comment by rennergade** [comment]
I believe I'm done moving `dup/dup2` to Safe Posix. I have a few good tests working and bash is now receiving file input where it wasn't working before.

There's still some debugging to do in bash so I'm going to wait to merge the `dup_fix` branch for now.

**Comment by rennergade** [comment]
This was closed with the `dup_fix` merge.
