### ISSUE TITLE
Implement SHM functions for Postgres

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#214]
It seems that we need some SYSV style shm functions for postgres to operate properly.

@kapkic can you provide more information here?

**Comment by kapkic** [comment]
Tracing this is a bit complicated - and far from perfect. I will include more details as uncovered.
Postgres uses the all of the 4 shm syscalls and 2 functions.
```
shm_unlink (3) - unlink (2)
shm_open (3) - open(2)
shmctl (2)
shmat 
shmget
shmdt
```
All of them are used at `lind_project\tests\applications\postgres\src\backend\storage\ipc\dsm_impl.c` (called from ipci.c), apart from a shm_open-unlink test in `initdb.c:911` just to check dsm implementation (returns POSIX, Windows or Sysv).

I am not able to provide verbosity on Lindside atm since we have other issues that won't allow us the variables to get to that point (fgets + fclose + and a signal 11 which I'm investigating)

There are a lot of function calls in shmem_x named functions. Generally they follow a path of `initdb.c->ipc.c/ipci.c->dsm.c->dsm_impl.c`
I'm also using gdb on a native build to see if there's anything else that can provide more detail.

**Comment by kapkic** [comment]
Occurences of shm functions `shm.*\(.*\)`:

```
~/lind_project/tests/applications/postgres/src/backend/storage/ipc/dsm_impl.c
  236,31: 		if (op == DSM_OP_DESTROY && shm_unlink(name) != 0)
  258,12: 	if ((fd = shm_open(name, flags, PG_FILE_MODE_OWNER)) == -1)
  303,3: 		shm_unlink(name);
  333,4: 			shm_unlink(name);
  498,16: 		if ((ident = shmget(key, segsize, flags)) == -1)
  522,34: 		if (*mapped_address != NULL && shmdt(*mapped_address) != 0)
  532,31: 		if (op == DSM_OP_DESTROY && shmctl(ident, IPC_RMID, NULL) < 0)
  548,7: 		if (shmctl(ident, IPC_STAT, &shm) != 0)
  560,12: 	address = shmat(ident, NULL, PG_SHMAT_FLAGS);
  568,4: 			shmctl(ident, IPC_RMID, NULL);
```
  
```
~/lind_project/tests/applications/postgres/src/bin/initdb/initdb.c
  911,13: 		if ((fd = shm_open(name, O_CREAT | O_RDWR | O_EXCL, 0600)) != -1)
  914,4: 			shm_unlink(name);
```

**Comment by jesings** [comment]
@rennergade believes he found a way that we would not have to support shm_open and shm_unlink, which would be helpful as they are mostly a different interface than the other shm functions. However, we would still need to support shmget/shmat/shmdt/shmctl.

[Here](https://docs.google.com/document/d/1-KdmXySkxQQds6F1EM-jQ7gZC8Zc5BRnr5FxyKKDt1U/edit) are some thoughts on how best to accomplish that.

**Comment by rennergade** [comment]
I've implemented the libc and NaCl portions of shmget/shmat/shmdt/shmctl (though I probably need to implement SHM_RND for shmat()).

I'll hopefully get this up and running with the rustposix part next week.

**Comment by rennergade** [comment]
Now have a draft up for RustPOSIX.

Still need to:
- properly do SHM_RND/SHM_REMAP
- Figure out shmat/shmdt/munmap interactions

**Comment by rennergade** [comment]
I have some basic tests of this working throughout Lind including sharing memory between cages/nexes. Will test fully tomorrow and should have a stripped down version of this by the weekend for @kapkic to start testing Postgres again.

**Comment by kapkic** [comment]
New shm patches pass the issue we had with Postgres.
At this point, we have 2 syscalls to patch:
1-chmod, executed at several files in initdb.c (just a return 0 would work, as our lind user always have access)
2-rename, executed after shmem, in origin.c _CheckPointReplicationOrigin_.
```
2022-05-09 18:27:02.271 EDT [17] PANIC:  could not rename file "pg_logical/replorigin_checkpoint.tmp" to "pg_logical/replorigin_checkpoint": Function not implemented
022-05-09 18:41:00.845 EDT [17] DEBUG:  building index "pg_toast_2600_index" on table "pg_toast_2600" serially
2022-05-09 18:41:00.845 EDT [17] DEBUG:  CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 1/1/238
2022-05-09 18:41:00.846 EDT [17] DEBUG:  shmem_exit(0): 1 before_shmem_exit callbacks to make
2022-05-09 18:41:00.846 EDT [17] DEBUG:  shmem_exit(0): 12 on_shmem_exit callbacks to make
2022-05-09 18:41:00.846 EDT [17] NOTICE:  shutting down
2022-05-09 18:41:00.846 EDT [17] DEBUG:  performing replication slot checkpoint
2022-05-09 18:41:00.848 EDT [17] PANIC:  could not rename file "pg_logical/replorigin_checkpoint.tmp" to "pg_logical/replorigin_checkpoint": Function not implemented

** Signal 11 from untrusted code: pc=58d501c96ec0
child process exited with exit code 137
```

I also wrote a simple test case to see if rename syscall is working; which gave an error on Lind.

**Comment by jesings** [comment]
I think we still have to deal with or justify the corner cases of partial unmaps/remaps

**Comment by rennergade** [comment]
Right, I was going to make a new issue for that since this one said "for postgres" but I got distracted... will do that now.
