### ISSUE TITLE
Add Bash/Coreutils based test suite

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#223]
We have some holes in our current testing because we don't test any more robust apps.

Let's build/load bash and coreutils and set up some tests in a similar way to our current test suite.

**Comment by kapkic** [comment]
Implemented with #229.

**Comment by rennergade** [comment]
Awesome!

Can we add the popen/pclose test to this?

I'll also set up the pipescript test so we can add those as well.

**Comment by kapkic** [comment]
Implemented with #231.

**Comment by rennergade** [comment]
Great!
