### ISSUE TITLE
Develop LAMP Test

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#233]
As per our discussion at the meeting on 4/13. We should start to develop a test case to use for evaluating LAMP stack speed.

@moyix suggested we do something that does a rapid SQL requests of a small size. We should be able to set this up with a Flask program using SQLalchemy somewhat easily. Should most likely do a loop of X INSERT's followed by a loop of X SELECT's.

Let's get a framework for this and set it up to test natively while we get psql working for Lind.

**Comment by Devansh-Patel** [comment]
I just developed a test doing 1000 inserts and 1000 selects in flask app and routed it through gunicorn/nginx and postgres. Here is the flamegraph. 
![lamp-graph](https://user-images.githubusercontent.com/45604637/194724479-52416cf2-6086-497a-878d-4cf291e070e3.svg)

**Comment by rennergade** [comment]
Cool, thanks for this @Devansh-Patel 

We probably need to think about refining this more. I think the first thing here is that just 1000 ops is not that many, since program startup seems to still dominate here. Also the fork cost seems to be extremely low, maybe we want to test with a lot of different connections?

**Comment by JustinCappos** [comment]
Are there existing web benchmarks commonly used by academics that we could
potentially also use?  This may make it easier when we write the paper...

**Comment by rennergade** [comment]
Thats a good idea, will look into this.

**Comment by rennergade** [comment]
@AlpacaMax lets see if you could find ~5 or so research papers that benchmark a LAMP stack or something similar. I'll review what you find with you.

**Comment by rennergade** [comment]
I reviewed the work that @AlpacaMax dug up. The benchmarking program [wrk](https://github.com/wg/wrk) seems to be used for HTTP benchmarks in a few papers and I think would be good for us to run. We could set up a page that calls to the DB for a few params and then run wrk on that page.

If we want to more thoroughly test just the DB [we probably want to get `pgbench` working.](https://github.com/Lind-Project/lind_project/issues/280)

**Comment by Devansh-Patel** [comment]
Here is the new flamegraph that I generated with wrk. I ran wrk with 12 threads, 400 connections to be kept open by each thread for a duration of 30 seconds. 

![wrk_perf](https://user-images.githubusercontent.com/45604637/205788555-9e1407e1-8d94-46ea-b452-bc5a17b8eceb.svg)

**Comment by RusherRG** [comment]
I used the Flask app setup by @Devansh-Patel as the base and wrote a benchmark script to calculate the syscall times for the LAMP stack. I found that the total syscall time increases as we increase the size of the queries. Also, increasing the number of threads and connections doesn't significantly affect the syscall times. 

The best configuration I found was:
- threads -> 4
- connections -> 4
- duration -> 60s
- size -> 65535
- number of queries -> 5

and the above configuration gave syscall values of **10.44057%** for ___x64_sys_recvfrom_ and **20.04988%** for ___x64_sys_sendto_ amounting to a total time of **30.49045%**  for I/O syscalls.

**Comment by rennergade** [comment]
Awesome job Rushang. These results look great. If 30% of a LAMP test is I/O I think we can show some real improvement.

**Comment by JustinCappos** [comment]
This is great news.  If it's not too hard to do, I'd love to see this also listed per benchmark in some LAMP stack benchmark-suite.  (This benchmark suite would also be a suite we would use in the paper.)

**Comment by rennergade** [comment]
This is using the [wrk](https://github.com/wg/wrk) benchmarker that @AlpacaMax found while searching through recent/relevant papers. I'm not sure there is a commonly used "suite". Do you know of any @JustinCappos ?

**Comment by JustinCappos** [comment]
Okay, great!  Looking at recent / relevant papers is exactly how I would say we should find the benchmark!

**Comment by rennergade** [comment]
We now have a benchmarker for this using wrk and a postgres heavy flask app thanks to @RusherRG
