### ISSUE TITLE
Pipe "Edge" Cases

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#24]
Now that we have pipe related fd's, we need to make sure syscalls that take an fd int do the right thing with them.

**These are handled by the basic pipe protcol**
int lind_pread(int fd, void* buf, int count, off_t offset, int cageid);
int lind_pwrite(int fd, const void *buf, int count, off_t offset, int cageid);
int lind_close (int fd, int cageid);
int lind_read (int fd, int size, void *buf, int cageid);
int lind_write (int fd, size_t count, const void *buf, int cageid);

**I believe these will need to be specifically handled**
int lind_lseek (off_t offset, int fd, int whence, int cageid);
int lind_fxstat (int fd, int version, struct lind_stat *buf, int cageid);
int lind_fstatfs (int fd, struct lind_statfs *buf);
int lind_dup (int oldfd, int cageid);
int lind_dup2 (int oldfd, int newfd);
int lind_getdents (int fd, size_t nbytes, char *buf, int cageid);
int lind_fcntl_get (int fd, int cmd);
int lind_fcntl_set (int fd, int cmd, long set_op);
int lind_flock (int fd, int operation);

**These socket related ones I believe already are handled by checking IS_SOCK**
int lind_bind (int sockfd, socklen_t addrlen, const struct sockaddr *addr);
int lind_send (int sockfd, size_t len, int flags, const void *buf);
int lind_recv (int sockfd, size_t len, int flags, void *buf);
int lind_connect (int sockfd, socklen_t addrlen, const struct sockaddr *src_addr);
int lind_listen (int sockfd, int backlog);
int lind_sendto (int sockfd, size_t len, int flags, socklen_t addrlen, const struct sockaddr_in *dest_addr, const void *buf);
int lind_accept (int sockfd, socklen_t addrlen);
int lind_getpeername (int sockfd, socklen_t addrlen_in, __SOCKADDR_ARG addr, socklen_t * addrlen_out);
int lind_setsockopt (int sockfd, int level, int optname, socklen_t optlen, const void *optval);
int lind_getsockopt (int sockfd, int level, int optname, socklen_t optlen, void *optval);
int lind_shutdown (int sockfd, int how);
int lind_select (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval *timeout, struct select_results *result);
int lind_recvfrom (int sockfd, size_t len, int flags, socklen_t addrlen, socklen_t * addrlen_out, void *buf, struct sockaddr *src_addr);
int lind_poll (int nfds, int timeout, struct pollfd *fds_in, struct pollfd *fds_out);

**Comment by rennergade** [comment]
It's also probably a good idea to handle how cageid is inserted into these stubs...

**Comment by JustinCappos** [comment]
Why is open handled by the basic pipe protocol?  It doesn't take a fd.

Also why don't some calls like dup2, fcntl*, etc. have cageids?

I'm also a little confused about how pipes and IS_SOCK relate...

**Comment by rennergade** [comment]
These are all good questions. I copied this from the `lind_platform.h` RPC signatures.

Open: Made a mistake and left that up there.

CageID stuff: This is a little more complex but basically the calls where cageid is in the signature are routed  through NaCl's descriptor system so they need to be given it as an Arg, the other calls go through a generic handler that inserts CageID. My comment above was an acknowledgement that this is pretty terrible software engineering.

SOCK: The point here is to make sure anything with an FD is handled correctly, all the socket calls are already checking if its a socket, which means its not a pipe, and thus won't do anything funky with it.

**Comment by Yash151** [comment]
I tried writing the code where one fd is of type pipe and the other is a normal one and tried for the following functions. Below are the findings:

int lind_lseek (off_t offset, int fd, int whence, int cageid);
If we provide an fd of type pipe then it will throw an error with errno 9 (bad fd)

int lind_fstatfs (int fd, struct lind_statfs *buf);
If we provide an fd of type pipe it throws an error with error no 9 (bad fd)

int lind_dup (int oldfd, int cageid);
This works fine if we provide an fd which is of type pipe

int lind_dup2 (int oldfd, int newfd);
This works fine if we provide an fd which is of type pipe

int lind_getdents (int fd, size_t nbytes, char *buf, int cageid);
If we provide an fd of type pipe then it will throw an error with errno (not a directory)

int lind_fcntl_get (int fd, int cmd);
This works fine if we provide an fd which is of type pipe

int lind_fcntl_set (int fd, int cmd, long set_op);
This works fine if we provide an fd which is of type pipe

int lind_flock (int fd, int operation);
This works fine if we provide an fd which is of type pipe

Was not able to find much info regarding the fxstat function.
Below is the sample code I used to check for getdents:
`#include <dirent.h> 
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#define BUF_SIZE 1024*1024*5
int main(int argc, char *argv[]{
int fd,ret,actual_ret,new_ret;
char buf[BUF_SIZE];
int mypipefd[2];
fd = open("Documents",O_RDONLY,O_DIRECTORY);
ret = pipe(mypipefd);
new_ret = syscall(SYS_getdents,mypipefd[0],buf,BUF_SIZE);
actual_ret = syscall(SYS_getdents,fd,buf,BUF_SIZE);
printf("pipe=%d\n",new_ret);
printf("non-pipe=%d",actual_ret);
}
`

**Comment by Yash151** [comment]
I tried checking what the functions do when passing them an fd of pipe type. Below are my findings. I wrote code to check the output when we pass an fd of type pipe:

int lind_lseek (off_t offset, int fd, int whence, int cageid);
If we provide an fd of type pipe then it will throw an error with errno 9 (bad fd)

int lind_fstatfs (int fd, struct lind_statfs *buf);
If we provide an fd of type pipe it throws an error with error no 9 (bad fd)

int lind_dup (int oldfd, int cageid);
This works fine if we provide an fd which is of type pipe

int lind_dup2 (int oldfd, int newfd);
This works fine if we provide an fd which is of type pipe

int lind_getdents (int fd, size_t nbytes, char *buf, int cageid);
If we provide an fd of type pipe then it will throw an error with errno (not a directory)

int lind_fcntl_get (int fd, int cmd);
This works fine if we provide an fd which is of type pipe

int lind_fcntl_set (int fd, int cmd, long set_op);
This works fine if we provide an fd which is of type pipe

int lind_flock (int fd, int operation);
This works fine if we provide an fd which is of type pipe

I was not able to get much info regarding the fxstat function. I have attached the code for checking the getdents function below:

[getdents.txt](https://github.com/Lind-Project/lind_project/files/3677902/getdents.txt)

**Comment by rennergade** [comment]
Thanks Yash. I agree that there's limited documentation to what `fxstat` is.

According to [this link](http://polarhome.com/service/man/?qf=STAT&af=0&tf=2&of=UNIXv7)
"When fildes is associated with a pipe, fstat reports an ordinary file with restricted permissions. The size is the number of bytes queued in the pipe."

**Comment by rennergade** [comment]
These have been handled on the `pipe-update` branch.
