### ISSUE TITLE
Implement AF_UNIX sockets

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#247]
We need [unix domain sockets working for postgres to run](https://github.com/Lind-Project/lind_project/issues/64#issuecomment-1132010735).

To do this we need to add the concept of socket inodes, and also change bind to access our Lind FS.

**Comment by JustinCappos** [comment]
Can you discuss more about why you need these?  Are these abstractions you
can just do away with and mock or is there something more complex that
needs to happen?

**Comment by rennergade** [comment]
Postgres uses domain sockets to communicate from client to backend. I believe nginx will also use them when we connect it with Python/Flask but haven't gotten there yet.

We need to build a bit of the infrastructure in RustPOSIX to support domain sockets connecting between programs because they rely on a path/inode to connect to each other. As of now we don't have inodes for sockets. We can still mock the actual sockets like were doing currently, and later replace that with the userspace implementation I talk about [here](https://github.com/Lind-Project/lind_project/issues/186).

**Comment by JustinCappos** [comment]
Okay, sounds good.  Just be sure to think about cases where we can optimize
and/or simplify to get a performance boost.

**Comment by rennergade** [comment]
I believe this is working. I have test cases that work in both the rust test suite and Lind. The postgres programs also seem to be working properly.

However I can't run them at the same time, which I'll write about in another issue.
