### ISSUE TITLE
I/O Address Unmapping Safety

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#288]
During I/O calls, we check the NaCl VMMap to make sure our buffer address is valid before we send the call to RustPOSIX. The gap between the address check and the actual pipe operation is a TOCTTOU bug that could result in a Trusted Fault, which we handle gracefully but results in Lind terminating. To ensure this doesn't happen, we have to make sure the buffer addresses cannot be umapped after the VMMap address check.

Fixing this issue without sacrificing performance in our worst case pipe scenarios is tricky, due to issues with deadlock/starvation and the cost of mutexes. Deadlock issues potentially arise from having I/O calls within the same cage (i.e Cage 1/Thread 1: in blocking read, Cage 1/Thread 2: attempts to write). While a potential starvation issue comes from locking out ALL mapping during a block I/O call (same as above, but thread 2 needs to map an area).

This issue has technically been around since the beginning of Lind. NaCl didn't worry about the vmmap check being preserved entirely for things such as read/write because they were handled by the kernel calls.

Since we never technically *unmap* any user addresses, what we are actually worried about are addresses being remapped as PROT_NONE, or mprotected to PROT_NONE (or changed to an invalid prot). The calls that could affect this to my knowledge are: mprotect(), mmap() (with MAP_FIXED), munmap(), and shmdt() (if the address was originally assigned as shared memory).

So altogether, we need to find a solution that:
1. Prevent the buffer address being unmapped between the address check and data being copied into/from the checked buffer
2. Prevent blocking I/O calls from causing deadlock with other I/O calls within a cage
3. Prevents starvation during blocking I/O calls with map calls
4. Doesn't incur further performance penalties to read()/write() calls, since our scenario where read and write buffers are 2^4 has only ~8% margin over native pipelines.

Currently there is one mutex in NaCl in the read/write pipe pathways. It's used to manage the NaClDescs, which I've talked about in the past. These mutexes take ~12% of each I/O call when buffers are small (2^4). This mutex doesn't handle any of the scenarios above, but could be replaced by another mutex can handle the desc concurrency as well as I/O in relation to mapping.

However, to be able to give rustposix access to other I/O calls when one is currently blocking, we'd have to design that mutex as a RWLock. Unfortunately testing these in C demonstrates results that are ~2.5x slower than normal mutexes, which is enough to cause a performance drop that kills the small buffer gains.

Solution A:
I implemented a solution using a counter where in I/O calls:
- A flag is set inside of an I/O call mutex 
- The Cage's I/O counter is incremented
- The mutex is released
- The call proceeds to RustPOSIX
- The counter is decremented

And inside of map calls:
- The mutex is grabbed
- If the counter > 0: spinlock until 0

This would solve deadlock between I/O calls but would still deadlock with combined blocking I/O and mapping.

Solution B:
A different solution would be similar to above, but instead of spinlocking, having the call return an error, such as EACCES or EAGAIN. This would be starvation free, but could possibly cause software to fail incorrectly.

Mythical Solution C:
A more correct solution would only block/fail unmapping calls that are in the same range as the address for the I/O call, but I haven't been able to brainstorm a solution that is both concurrency safe and doesn't cause additional performance overhead.

I'm leaning towards Solution B currently but would like to open this up for some discussion.

**Comment by rennergade** [comment]
I think I've figured out a simple solution here.

When our signal handler catches the SIGSEGV, it assumes its a trusted fault because it happens within RustPOSIX. [However, siginfo provides information on what address caused the fault](https://stackoverflow.com/questions/3003339/how-can-i-get-gdb-to-tell-me-what-address-caused-a-segfault).

I should be able to check if the signal is SIGSEGV and if so check if the fault address is within our cage memory space. If so, I can change the teardown mechanism to be for an untrusted fault, and therefore only need to teardown the faulting cage and not the whole system.

**Comment by rennergade** [comment]
I was able to implement a fix for this issue, though it took some headscratching for a bit. Apparently, `PTHREAD_CANCEL_ASYNCHRONOUS` seems to not be on by default after the libc 2.34 update which was causing the teardown handler not to work as it previously did (looking into this a bit more it was weird that it WAS set before). This will also let me fix the [exiting threads on exit() call issue](https://github.com/Lind-Project/lind_project/issues/285) somewhat simply, and I will do that shortly.

There are some good things and bad things here, and I want to fully discuss them before I merge these changes. I want to be clear that the problems here don't specifically apply to the above issue but apply to the notion of being able to safely remove ANY faulting cage without having to abort Lind fully (as well as being able to properly exit multi-threaded cages in blocking cases).

The Good:
- Cancellation of a thread in Rust invokes Unwind which nicely cleans up any resources we have there.
- As all NaCl pthreads are launched as detached, thread resources also should properly get cleaned up (and we free the cage shared resources before freeing the nap structure)

The Bad:
Actually having to enable `PTHREAD_CANCEL_ASYNCHRONOUS` led me down a rabbit hole about this setting where the responses vary from "there be dragons here" to "this is never safe" to "well... this sometimes can be fine".

According to the [manpage](https://man7.org/linux/man-pages/man3/pthread_setcancelstate.3.html)

```
 Asynchronous cancelability
       Setting the cancelability type to PTHREAD_CANCEL_ASYNCHRONOUS is
       rarely useful.  Since the thread could be canceled at any time,
       it cannot safely reserve resources (e.g., allocating memory with
       malloc(3)), acquire mutexes, semaphores, or locks, and so on.
       Reserving resources is unsafe because the application has no way
       of knowing what the state of these resources is when the thread
       is canceled; that is, did cancellation occur before the resources
       were reserved, while they were reserved, or after they were
       released?  Furthermore, some internal data structures (e.g., the
       linked list of free blocks managed by the malloc(3) family of
       functions) may be left in an inconsistent state if cancellation
       occurs in the middle of the function call.  Consequently, clean-
       up handlers cease to be useful.

       Functions that can be safely asynchronously canceled are called
       async-cancel-safe functions.  POSIX.1-2001 and POSIX.1-2008
       require only that pthread_cancel(3), pthread_setcancelstate(),
       and pthread_setcanceltype() be async-cancel-safe.  In general,
       other library functions can't be safely called from an
       asynchronously cancelable thread.

       One of the few circumstances in which asynchronous cancelability
       is useful is for cancellation of a thread that is in a pure
       compute-bound loop.
```

**Comment by JustinCappos** [comment]
If the execution is within a cage and we are cleaning up that cage, I think this is always safe.  Even if malloc, etc. are happening, the resulting memory doesn't matter because the pages will just be unmapped.

We do need to handle the case where a call is in RustPOSIX.

**Comment by rennergade** [comment]
I definitely think this is safe in terms of resources shared between threads within a cage which are suspended and removed. There also aren't any resources shared between cages that could cause problems. What I am slightly worried about is problems within the trusted system's glibc ie a thread is canceled within the trusted malloc which messes up state somehow.

I don't think this example is actually a problem with how malloc is implemented with threads now, but thinking of things along these lines.

**Comment by JustinCappos** [comment]
Note, if we can suspend / resume threads as we desire (i.e.,
co-scheduling), this problem becomes a lot more manageable.

I'm thinking we can do this only in cages, not in the microvisor.

**Comment by rennergade** [comment]
After great conversations with @moyix and @JustinCappos yesterday I think I've found a solution based on some of their suggestions and a few other insights.

I'm able to toggle the thread such that once the flag is set I can inhibit code from passing from untrusted to trusted, or vice versa. This is useful because I can lock untrusted code in an untrusted state, and can cancel threads at this point usint pthread_cancel with the ASYNC flag. We can set all threads to be ASYNC cancellable, but only use pthread_cancel for threads we know are in untrusted space.

Otherwise, I've set up our own version of cancel points where we can tell a thread that should be torn down to safely exit. I have these positioned at the entry/exit points of syscall handlers, but we should also be able to add them at places we've designed to block (ie inside pipe_read/pipe_write loops). There's still some design hardships I need to work out with calling the NaCl cancel function from inside Rust but this all should be doable.

This should handle most cases for untrusted teardowns, though there are still some corner cases such as threads stuck in a blocking recv() (we can probably redesign blocking recvs with a select loop and a cancel point inside). I think this will be the safest way to handle this without leaving cages hanging or doing unsafe cancels.

**Comment by rennergade** [comment]
I believe this is all implemented for crashes and properly exiting thread groups. I probably am going to need to add a counter/timer to the cancel point in pipe_read so it doesn't trigger every iteration, because that would probably add a ton of overhead.

Going to test a bit more before putting up a PR.

**Comment by rennergade** [comment]
While merging and testing this I found that besides pipe read/recv, theres also possible hang up points in RustPOSIX for condvars and mutexes. @jesings is going to fix up the implementations there so that we can periodically check cancel points.

**Comment by rennergade** [comment]
This is finally fixed with the recent cancellation PR.
