### ISSUE TITLE
Compile libffi for ctypes (flask/Jinja2)

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#301]
We're almost able to get a full flask app running, but it segfaults whenever it tries to use the jinja2 function `render_template`. It seems to use the ctypes module which wraps libffi, and segfaults somewhere in libffi.

naclports shows the following changes to get this working:
[libffi](https://chromium.googlesource.com/external/naclports.git/+/570964f2ea67d1fbab419301f8873628f78e9c33/ports/libffi/nacl.patch) 
[python](https://chromium.googlesource.com/external/naclports.git/+/570964f2ea67d1fbab419301f8873628f78e9c33/ports/python/nacl.patch)

I'm hoping we can try some of the same changes to get this working.

A good first step would be making these changes, and compiling python with this module. Lets start with a simple test running a py file that imports libffi instead of trying to run flask and the whole stack.

**Comment by RusherRG** [comment]
@jesings had applied the patches mentioned above in the [simple_web_example](https://github.com/Lind-Project/lind_project/tree/simple_web_example) branch but the flask `render_template`  function was still segfaulting. 

I looked into the issue further and compared the changes done to the patch and changed a few things that were missed from the patch. After exploring further, I came across a particular comment at the end of [ctypes/\_\_init\_\_.py](https://github.com/Lind-Project/lind_project/blob/simple_web_example/tests/applications/python/Lib/ctypes/__init__.py#L545) file. Based on the comment I tried commenting the last line.
```py
# XXX for whatever reasons, creating the first instance of a callback
# function is needed for the unittests on Win64 to succeed.  This MAY
# be a compiler bug, since the problem occurs only when _ctypes is
# compiled with the MS SDK compiler.  Or an uninitialized variable?
CFUNCTYPE(c_int)(lambda: None)
```

This fixed the segfault issue. I tried running test script using jinja to render templates and also a flask app with `render_template` and everything seems to be working. Now I'm planning to test the entire stack with the latest changes.

**Comment by rennergade** [comment]
This was fixed awhile ago but was never closed
