### ISSUE TITLE
Compile with nacl-clang

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#318]
So far we've been using nacl-gcc, but there is some documentation about using nacl-clang to compile executables. Unfortunately all the documentation is for pnacl, which doesn't use libc. Despite this, I think it may be possible to compile nexes with nacl-clang and include nacl-libc as a shared library. This would be useful for two separate problems.

1. We've been having some problems on the iPC project because the compiled user code is slow. If we can get any gains here using clang over nacl that would be incredible.

2. For the library isolation project, we've seen some paper that use LLVM-IR code to analyze memory placement for libraries. If we have a working nacl-clang/nacl-llvm we could possibly apply these strategies to this project as well.

@kuzeyardabulut has been working on getting nacl-clang to work and has made some progress, but is stuck getting libc to be loaded as a shared library. He's going to attach some more details to this issue.

**Comment by kuzeyardabulut** [comment]
Hello,
I've prepared a Google document addressing this issue. You can access it through the [provided link](https://docs.google.com/document/d/18ev3aXhBeqfCvXdCTsxeT6hlA4b1vmOJJcrgYadMPiI/edit?usp=sharing).

**Comment by rennergade** [comment]
@moyix Kuzey has updated the document at the above link to be a bit clearer about where we are in this process. It looks like we've come pretty far but its still erroring when we try to compile as an executable.

If you have any thoughts we'd love to hear them.

**Comment by rennergade** [comment]
From speaking a bit with @moyix  about this, he had a nice idea to try and break this down and isolate the linker stage more.

@kuzeyardabulut let's try to see if we can compile to asm with nacl-clang, but do the linking stage with nacl-gcc. Since we know we can make asm with nacl-clang, and know we can link with nacl-gcc this may be a workaround.

**Comment by kuzeyardabulut** [comment]
Finally, we successfully compiled the object files with nacl-clang and linked them using nacl-gcc to obtain a dynamically linked .nexe file, thereby gaining access to LLVM Intermediate Representation (IR).

**Comment by kuzeyardabulut** [comment]
You can compile your own .c files like this:
```
[root@6717f1c8e245 ~]# /nacl_sdk/pepper_49/toolchain/linux_pnacl/bin/x86_64-nacl-clang -target "x86_64-nacl" hello_world.c -o hello-libc.o -c
[root@6717f1c8e245 ~]# /nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/x86_64-nacl-gcc hello-libc.o -o kk.nexe
[root@6717f1c8e245 ~]# cd /nacl_sdk/pepper_49/tools/
[root@6717f1c8e245 tools]#  python2.7 sel_ldr.py ~/kk.nexe
('CMD:', ['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe'])
['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe']
Hello, World!
['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe']
Hello, World!
['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe']
Hello, World!
['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe']
Hello, World!
['/nacl_sdk/pepper_49/tools/nacl_helper_bootstrap_x86_64', '/nacl_sdk/pepper_49/tools/sel_ldr_x86_64', '--r_debug=0xXXXXXXXXXXXXXXXX', '--reserved_at_zero=0xXXXXXXXXXXXXXXXX', '-q', '-a', '-B', '/nacl_sdk/pepper_49/tools/irt_core_x86_64.nexe', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib/runnable-ld.so', '--library-path', '/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/usr/lib:/nacl_sdk/pepper_49/lib/glibc_x86_64/Release:/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/x86_64-nacl/lib', '/root/kk.nexe']
Hello, World!
0.0137880325317
```

**Comment by yzhang71** [comment]
We are now trying to cross compile the application "grep", here are the breakdown steps:
1. export CC="/nacl_sdk/pepper_49/toolchain/linux_pnacl/bin/x86_64-nacl-clang -target x86_64-nacl -fPIC"
export CXX="/nacl_sdk/pepper_49/toolchain/linux_pnacl/bin/x86_64-nacl-clang++ -target x86_64-nacl -fPIC"
Using x86_64-nacl-clang to compile source code and obtain object file.
2. export LD="/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/x86_64-nacl-gcc"
export CCLD="/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/x86_64-nacl-gcc"
Linking object files with x86_64-nacl-gcc
3. Above steps will generate "undefined reference" error, such as:
/home/lind/lind_project/tests/applications/grep/lib/chdir-long.c:126: undefined reference to `__assert_func'
/home/lind/lind_project/tests/applications/grep/lib/chdir-long.c:145: undefined reference to `__errno'
/home/lind/lind_project/tests/applications/grep/src/grep.c:393: undefined reference to `_impure_ptr'
grep.o: In function `fwrite_errno':
searchutils.o: In function `kwsinit':
/home/lind/lind_project/tests/applications/grep/src/searchutils.c:48: undefined reference to `__locale_mb_cur_max'
/home/lind/lind_project/tests/applications/grep/src/searchutils.c:51: undefined reference to `__locale_mb_cur_max'
/home/lind/lind_project/tests/applications/grep/src/searchutils.c:53: undefined reference to `__ctype_ptr__'
collect2: ld returned 1 exit status
make: *** [Makefile:1307: grep] Error 1
4. I have diagnosed that the error is due to clang and gcc generate different symbols, take grep.o as an example, clang generate "errno" as "__errno" in object file, but gcc generate "errno" as "__errno_location" in object file

In general, the problem is gcc cannot recognize some symbols in object file that generated by clang compiler. And the current solution I am using is replacing some object files (grep.o and searchutils.o) with gcc version, and the rest 4 object files (.o), which are dfasearch.o, kwsearch.o, kwset.o, pcresearch.o using clang version. And then linking with x86_64-nacl-gcc. Please share any advice or opinions you have regarding the above approach. Thank you!

**Comment by rennergade** [comment]
@moyix any ideas here ^

Im guessing that compiling objects with clang is adding the wrong symbols for libc? I'm not sure what we would need to add to alleviate that

**Comment by moyix** [comment]
Hmm, I don't feel like that's exactly the issue – the object file format is independent of the compiler and the naming is standardized. So if there are different names being generated by the two compilers, it's (at some level) a difference in names in the source code.

However, that might not be something obvious. For example, clang and gcc might have different search paths for the system header files, and so compiling with one could be pulling in a different definition of errno than when compiling with the other.

For `errno` specifically:

The `__errno` variant seems to be the version used by newlib:

https://github.com/eblot/newlib/blob/master/newlib/libc/include/sys/errno.h#L13C1-L16C7

Whereas glibc uses `__errno_location`:

https://github.com/bminor/glibc/blob/master/stdlib/errno.h#L36-L38

So at a guess, nacl-gcc is trying to use glibc headers, and nacl-clang is trying to use newlib headers.

**Comment by yzhang71** [comment]
By changing the include path of x86_64-nacl-clang, we are now able to compile "grep" with clang, and link with gcc:
```
export CC="/nacl_sdk/pepper_49/toolchain/linux_pnacl/bin/x86_64-nacl-clang -target x86_64-nacl \
-I/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/../lib/gcc/x86_64-nacl/4.4.3/include \
-I/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/../lib/gcc/x86_64-nacl/4.4.3/include-fixed \
-I/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/../lib/gcc/x86_64-nacl/4.4.3/../../../../x86_64-nacl/include"
export CFLAGS='-DO_BINARY=0 -DO_SEARCH=0 -DO_TEXT=0 -DS_TYPEISTMO\(p\)=0 -g -fno-pie'
```
But we still need to manually define some Macros and change variables name, due to the compiler's difference. To make it easier, I used "sed" as shown below:
``` 
sed -i 's/gettimeofday (struct timeval \*restrict tv, void \*restrict tz)/gettimeofday (struct timeval *__restrict tv, struct timezone *__restrict tz)/g' ./lib/gettimeofday.c
sed -i 's/static void _GL_ATTRIBUTE_FORMAT_PRINTF (3, 0) _GL_ARG_NONNULL ((3))/\/\/ &/' ./lib/error.c
sed -i '1i typedef size_t __re_size_t;' ./lib/regex_internal.h
sed -i 's/_Restrict_/restrict/g' ./lib/regcomp.c
sed -i 's/_Restrict_/restrict/g' ./lib/regexec.c
sed -i '1i\
#ifndef _GL_ATTRIBUTE_FORMAT_PRINTF\n\
#define _GL_ATTRIBUTE_FORMAT_PRINTF(x,y)\n\
#endif\n' ./src/grep.c
sed -i 's|CCLD = $(CC)|CCLD="/nacl_sdk/pepper_49/toolchain/linux_x86_glibc/bin/x86_64-nacl-gcc"|' ./src/Makefile.in
```

**Comment by rennergade** [comment]
It seems like we're able to do this. I'm not sure when we'll need to use this in the near future but we should save all the information on how to compile programs with clang in one place so we don't lose it. @yzhang71 can you do that? Otherwise this issue can be closed.

**Comment by yzhang71** [comment]
Yes, this issue can be closed. I have documented the compilation process.
