### ISSUE TITLE
NaCl Strace

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#319]
As discussed the in the meeting today lets make a way to create a NaCl strace. The output should look as close as possible the output to calling strace on a program so we can compare Lind results to native.

The easiest way to do this would be adding some ifdefs top native client so that if we compile the sel_ldr with the strace option defined, it will print the trace to a trace file.

We can put these prints  in nacl_syscall_common.c for every syscall ie NaClSysOpen. These should output the cageid as pid, and the syscall name/number as well as any other info that native strace does.

Later on lets try to take this trace and possibly create a record replay system.

**Comment by JustinCappos** [comment]
I had a few thoughts and wanted to chime in.  (Feel free to push back if you disagree.)

I wouldn't stress too much about looking like strace.  It does a bunch of odd things in places for historical reasons and it isn't very suitable for replay.  I would focus on easy to serialize / deserialize over being easy to read.

If you have serialized information, you can have a utility that prints this file in a nicely readable way which could be close to strace, if you desire.  Being able to replay is the main goal, of course.

**Comment by rennergade** [comment]
Just seeing this.

I think trying to mirror strace would be really handy because then we could easily compare log files side by side. From our debugging experience this seems really useful and not that difficult for Coulson to implement.

The replay seems like a cool idea but seems like it could become a huge project which might not be the best allocation of resources. Once the new server is up I'll be able to tell if we can have Lind run some of these bigger application suites (ie the LAMP stack) in RR without crashing. If we can use RR then our handrolled replay wouldn't really be useful.

**Comment by rennergade** [comment]
This was completed by @yizhuoliang @yashaswi2000 @rupeshkoushik07 

Great job guys
