### ISSUE TITLE
Implement fsync()

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#336]
We're having some problems seemingly with file syncing in postgres. We currently have been turning the fsync option off for it to be able to run, since we don't implement it. This seems like its most likely causing the problem.

Let's implement fsync(), we should add a syncing mechanism to file.rs in the interface and wrap it with a system call.

**Comment by kuzeyardabulut** [comment]
fdatasync and fsync syscalls are implemented.
#338

**Comment by rennergade** [comment]
Thanks for that @kuzeyardabulut !

Apparently for postgres to work we also need to patch in sync_file_range. It seems like the easiest way to do that is to wrap the libc function.

**Comment by rennergade** [comment]
This was completed by @kuzeyardabulut thanks!
