### ISSUE TITLE
More Strace Fixes

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#345]
We found a few errors in the strace feature which @rupeshkoushik07 is working on. Making an issue to keep track of progress.

Step 1: Fix existing issues

1a. Ordering issue
We found that some of the args were being printed in a different order than how they appear in the syscall. Rupesh is attempting to match those to how the appear on each syscalls manpage.

2a. Signing issue
We're seeing that some calls are returning large numbers where we think they should be returning negative numbers (errnos). There seems to be some signing/conversions issues that I'm not sure about. Can you look into this and fix it?

```
15 stat(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset/0.1, 0x7f4f68538730) = 4294967294
15 open(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset/0.0, 578, 384) = -2
15 mkdir(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset, 448) = 0
16 stat(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset/1.1, 0x7f4f68322730) = 4294967294
16 open(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset/1.0, 578, 384) = -2
16 mkdir(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset, 448) = 4294967294
16 mkdir(base/pgsql_tmp/pgsql_tmp15.0.sharedfileset, 448) = 4294967294
```

Step 2: Implement strace -c functionality

We want to implement functionality like strace does with -c. This lists all the calls that are made and the amount of times each called is made as well as the average time.

For example this is the -c output for 'ls'
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0         7           read
  0.00    0.000000           0       150           write
  0.00    0.000000           0        12           close
  0.00    0.000000           0        11           fstat
  0.00    0.000000           0        28           mmap
  0.00    0.000000           0         8           mprotect
  0.00    0.000000           0         1           munmap
  0.00    0.000000           0         5           brk
  0.00    0.000000           0         2           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         2           ioctl
  0.00    0.000000           0         8           pread64
  0.00    0.000000           0         2         2 access
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2         2 statfs
  0.00    0.000000           0         2         1 arch_prctl
  0.00    0.000000           0         1           futex
  0.00    0.000000           0         2           getdents64
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0        10           openat
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000                   258         5 total
```
To do this we need to do several things

1. Have lind accept a flag to turn this setting on (@yizhuoliang can you show rupesh how to do this), and set a global boolean to true
2. setup a system probably using arrays to store the count and total time for each call
3. for each strace function, if the boolean is set, increment the count and record start and end times for the call, add the difference in a time array to total it
4. at the end, format and print the stats

**Comment by rupeshkoushik07** [comment]
This issue has been addressed in the following  [PR](https://github.com/Lind-Project/native_client/pull/152)

**Comment by rennergade** [comment]
This was completed by @rupeshkoushik07 . Thanks for your help! He's even added sortable -c output.
