### ISSUE TITLE
Set environment variables

### ISSUE THREAD

**Issue by Yaxuan-w** [Lind-Project/lind_project#349]
Thanks for the talk earlier about environment variables. After our conversation, I found the source code of `getenv()` [[link](https://github.com/Lind-Project/Lind-GlibC/blob/develop/stdlib/getenv.c)] and `setenv()` [[link](https://github.com/Lind-Project/Lind-GlibC/blob/main/stdlib/setenv.c#L42)] in lind-glibc. I made some tests within lind and found that they work fine - changes to env vars are process-local though.

I discovered a file named `/posix/environ.c` [[link](https://github.com/Lind-Project/Lind-GlibC/blob/main/posix/environ.c#L1)] that seems to be responsible for setting environment variables during initialization. I'm considering modifying this file to set environment variables in lind.

I'd like to hear what thoughts @yzhang71 @rennergade and @JustinCappos have on if this approach is feasible or if there might be a better way to achieve this.

**Comment by JustinCappos** [comment]
This makes sense to me.  You might also see what other versions of glibc do
with respect to this code.
