### ISSUE TITLE
Failing Signal Tests

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#350]
```
Some tests have failed.
2 deterministic tests and 1 non-deterministic tests have failed.
Failed tests:
uds-serverclient.c sigpipe.c uds-socketselect.c
make: *** [Makefile:56: test] Error 1
```

There seem to be a few tests failing the test suite after the mega-merge. Let's find out why and fix them.

**Comment by rennergade** [comment]
I took a quick look at this. I think the uds-tests are just failing because the outputs aren't being correctly compared, so should be easier fixes.

The sigpipe test seems to not be working correctly though and I don't really know why. That probably requires some debugging.

@mayank-ramnani can you look at this with @yashaswi2000 we're hoping to fix these up so we can get the CI and builds running again.

If you guys have any questions feel free to ask @RusherRG @yizhuoliang and I

**Comment by mayank-ramnani** [comment]
Raised PR 357 that fixes uds-socketselect and uds-serverclient tests.
Issue was due to order of output being different within runs, and between native client and lind runs approximately 1/5 times.

Sigpipe test has been fixed in another PR: https://github.com/Lind-Project/native_client/pull/159
