### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#4]
Update README to better reflect how to build/run lind. Utilize wiki's if useful.

**Comment by jesings** [comment]
The main README has not been edited, as it mostly reflects how to install lind. However, instructions on how to use lind have been included within docs/README.md and the utility scripts necessary to follow the instructions have been placced in src/scripts.

**Comment by rennergade** [comment]
Keeping this open for now. I'll update the main README when the new docker image gets uploaded.
