### ISSUE TITLE
Update Wikis/README

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#55]
We need better instructions on building, installing, and running Lind, as well as how the infrastructure works.

This will also serve as good onboarding process.

As a first task - let's update the build/install/and run pages

**Comment by rennergade** [comment]
I've created this wiki as a template:

https://github.com/Lind-Project/lind_project/wiki/Installing-and-Running-Lind

**Comment by rennergade** [comment]
It's probably best that you two collaborate on a google doc first and I'll review from there as opposed to editing the wiki directly.

**Comment by mzhang15** [comment]
Here is a markdown file I created that detailed the steps to take to
compile and run a program in lind for the first time. Let me know what you
think and if I need to break those steps down to the 3 sections,
installing, compiling and running, that are listed in the template.

**Comment by rennergade** [comment]
Great! That's updated.

The next step is to get you guys familiar with the internals of Lind.

What I'd like for you both to do is compile a bunch of the test cases, and then run them with GDB. You can see instructions on how to run Lind in GDB in the "Debuggin Techniques" wiki.

Use the "Lind Architectural Description" wiki as a starting point to start to map out how Lind is working. Look at how system calls are intercepted, and how we use RPC to send information to SafePOSIX. 

I'm hoping this will get both of you much more familiar with what we're doing here, and also will yield a much more thorough "Lind Architectural Description" wiki. I would love to see some images created that map this out if one of you is up to that task!

**Comment by rennergade** [comment]
This will also helpfully check this issue off the list: https://github.com/Lind-Project/lind_project/issues/31

**Comment by rennergade** [comment]
This was updated earlier this week.
