### ISSUE TITLE
Debug Postgres

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#64]
SQLite is lightweight and easy to configure. I think this is a good choice for the "M" portion of our source code.

We need to add the source code to our applications folder and try to bootstrap it.

**Comment by rennergade** [comment]
Changing this issue from SQLite to Postgres, since it seems like SQLite wont demonstrate the behavior we want to prove.

We should as a first step download compatible postgres source code to tests/applications, and try to port `bootstrap_nacl`

**Comment by youngfalcon** [comment]
Current problem:

`checking for /dev/urandom... configure: error: cannot check for file existence when cross compiling`

**Comment by rennergade** [comment]
via @jesings https://stackoverflow.com/questions/61756501/unable-to-cross-compile-postgresql-12-2-for-arm

**Comment by youngfalcon** [comment]
Postgres was updated and built in the branch Postgres-build.

There was no warning in the making process. However, the installation has not yet been followed through and there has not yet been any conclusive testing.

**Comment by rennergade** [comment]
Ok great, so this builds!

This is a bit more complicated than past apps since it compiles into multiple executable tools including: initdb, psql, pg_ctl, and the actual postgres app. It also generates a library that I had to load into the fs.

Some first error messages:

From running initdb:

```@(1:107) $ lind /bin/pg/initdb -D pgsql/data

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/pg/initdb -D pgsql/data]
Lind v1.0-rc2
Opening file system...
done.
[25372,2117268544:13:02:42.633889] BYPASSING ALL ACL CHECKS
could not identify current directory: Function not implemented
could not identify current directory: Function not implemented
could not identify current directory: Function not implemented
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "initdb".
Check your installation.
Persisting metadata: ...
Done persisting metadata.
Terminated
```

From running postgres standalone:

```@(1:108) $ lind /bin/pg/postgres

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/pg/postgres]
Lind v1.0-rc2
Opening file system...
done.
[25469,4054295616:13:05:12.334001] BYPASSING ALL ACL CHECKS
LOG:  XX000: could not identify current directory: Function not implemented
LOCATION:  find_my_exec, exec.c:137
postgres: real and effective user IDs must match
Persisting metadata: ...
Done persisting metadata.
Terminated
```

It seems like the error is coming from invoking ioctl() which we don't handle. This also was looking like the cause of the error for this bug: https://github.com/Lind-Project/lind_project/issues/60

**Comment by rennergade** [comment]
Successfully built! Changing this issue to "Debug"

**Comment by rennergade** [comment]
I'm mistaken the sort error was in fcntl and not ioctl.

**Comment by rennergade** [comment]
Postgres builds! Getting an error running version. I'm not sure libpthread got installed for some reason?
```
@(1:219) $ lind /bin/psql -version

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/psql -version]
[229,2971953152:17:20:19.839086] BYPASSING ALL ACL CHECKS
/bin/psql: error while loading shared libraries: libpthread.so.990e7c45: cannot open shared object file: Operation not permitted
```

**Comment by rennergade** [comment]
I think something is wrong with the buildscript loading the major libraries into /lib and /usr/lib

Anyways, once I did that I got a version!

```@(1:227) $ lind /bin/psql --version

executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/psql --version]
[1410,3927414784:17:30:36.065788] BYPASSING ALL ACL CHECKS
could not identify current directory: Function not implemented
psql (PostgreSQL) 13.0
```

Though we need to add getcwd which Caglar is working on.

**Comment by rennergade** [comment]
It seems like we've gotten past the shared memory issues. We're now here: https://github.com/Lind-Project/lind_project/issues/214#issuecomment-1121656200

**Comment by rennergade** [comment]
So after a marathon debug session, I've finally got initdb and postgres to work without crashing/hanging. And we actually initialize a real database in Lind!

The actual postgres backend is currently failing gracefully because we don't implement domain sockets yet for socket(). We talk about how we want to improve upon this [in this issue](https://github.com/Lind-Project/lind_project/issues/186), but for now I'm going to set this up the way we do it in socketpair which is faking them with IP sockets. 

This seems close!!

**Comment by rennergade** [comment]
I believe domain sockets are working properly now. But when I went to test postgres (backend + psql) I realized that we can't actually run two programs in parallel through bash. We don't have a concept of a background process, so we never launch the second program while the first is running and waiting in select.

It didn't dawn on me that we had never tested this, though it makes sense since we don't implement a lot of the functions that make backgrounding possible. I think this isn't a huge issue but I need to figure it out. We don't have stdin and dont really need process groups so I think I just need to disable whatever is causing it to wait on a program when launched before forking the next one, which shouldnt be a terrible hack.

**Comment by rennergade** [comment]
Aha, the problem was we hadn't implemented WNOHANG for wait, which was a simple fix.

Now I can run in parallel. psql isn't connecting correctly so need to dig in deeper there.

**Comment by rennergade** [comment]
Despite fixing the above errors there's still some wonkiness going on where postgres unexpectedly closes the client connection. I'm slugging through this but debugging isn't the easiest with a program of this size and complexity.

**Comment by rennergade** [comment]
The above was a bug when running with localhost enabled (default) and was fixed by not allowing tcp connections. It was triggered because it seems like localhost uses NETLINK for getaddr. I'm not seeing any explicit errors yet and comparing to native its close to the workings state but seems to be stalling near the end now.

**Comment by rennergade** [comment]
Ah, so weirdly postgres uses SIGCHLD to attach a reaper function on child exit that unfortunately is vital for the postgres startup to complete.

I think my options here are either patch the postgres code manually to have it call the reaper on exit, or actually implement SIGCHLD which is probably actually possible to do much more than other signals, but still may take some time.

**Comment by rennergade** [comment]
I misdiagnosed this, since its been awhile since I worked with a SIGCHLD handler, I was confusing it with the behavior of [pthread_cleanup](https://man7.org/linux/man-pages/man3/pthread_cleanup_push.3.html) which has the thread do something on exit, not have an exiting process signal to the parent which doest the handler routine. So both the solutions I wrote above don't actually make sense.

I'm actually coming up blank for how we can actually handle SIGCHLD effectively, which is very frustrating because this is most likely the last thing blocking postgres from running (and by extension the whole LAMP stack).

**Comment by rennergade** [comment]
The reaper function I describe above can be found [here](https://github.com/Lind-Project/lind_project/blob/78a3f8040407b95c5c33005dfb723c5795419183/tests/applications/postgres/src/backend/postmaster/postmaster.c#L2923)

**Comment by rennergade** [comment]
So I was able to get the backend to work by adding the reaper to the postgres's serverloop instead of relying on SIGCHLD. At this point it seems like the backend is working properly and psql and other utilities are able to connect to it.

I'm unable to interact with the backend currently though because I keep on getting the error message `FATAL:  role "lind" does not exist` where lind is the hostname/username used to setup initb.

**Comment by rennergade** [comment]
This is actually a very weird bug that starts way earlier in the program. pgstat is a socket that is used for stats and a credentials and is opened early on. A bit later a call to getifaddrs() fails (because [its not properly implemented](https://github.com/Lind-Project/lind_project/issues/255)) and libc somehow buggily closes fd 0 (where pgstat is opened, after a stdin close) even though its not involved.

Later on in the program we can't use the pgstat fd to retrieve info and the credential check breaks.

I'm pretty sure this is the last bug until postgres is fully running. The server starts up and accepts connections, and can transmit data, and the database seems to be properly initialized otherwise. I've tried several utility programs and they seem to be working otherwise as well.

**Comment by rennergade** [comment]
So it seems that we need to enable the LKM for shared memory to work properly here (duh). Once that's enabled the forked connection has access to the database.

This is more good news/bad news. 

The good news is tremendous, postgres appears to be working!
The bad news is the LKM is still buggy and we're going to be dealing with server issues.

**Comment by rennergade** [comment]
With the recent shared memory fixes, @jesings has the backend running with client applications able to connect. Were still testing for actual functionality, first trying to get postgres's benchmark program `pgbench` to work.

**Comment by rennergade** [comment]
We can connect, create db, insert, and select now via psql.

I'm going to mark this issue as closed and open up a side pgbench issue.
