### ISSUE TITLE
Implement pipe

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#8]
Setting up a user-space pipe implementation will provide us robustness, as well as hopefully increasing efficiency, by eliminating the need for context switches.

Cross reference to https://github.com/Lind-Project/nacl_repy/issues/11

**Comment by rennergade** [comment]
Some work on this had been done with this PR https://github.com/Lind-Project/nacl_repy/pull/13

We'll need to determine whether to use this as a spring board or start from scratch.

**Comment by rennergade** [comment]
Per talk w/ Justin:

1. This should be implemented in memory, not using lindfs (pipes in Linux normally use their own FS)
2. A rudimentary implementation might just use a string as the pipe to store information, using defined MAX_SIZE, and locks.

**Comment by rennergade** [comment]
Per meeting on 8/8/19:

The trick here will be finding a place, on the repy side, to store the pipe data-structure in memory that both persists and is accessible by multiple processes.

@detectivelyw  suggested that the FS handler runs for the lifetime of a lind execution, so this may be a good place for implementation.

**Comment by JustinCappos** [comment]
I'm a little confused about the question.  Is this just about where in the
code to add it to make it the cleanest possible?  In all cases I think this
just a buffer in the microvisor (safe_posix code running in Repy), but if
you want to move pipe to another module that imports, I think this may be
fine.

My thinking is that it works something like this:

There is some dict in the microvisor that contains the status of the
buffers, etc.

There is a handle to this internally kept by the processes when they create
a pipe.

Read and write operations use that handle to manipulate the dict's buffer
and block / return data / write data as needed

Close operations are tracked and clean up the dict when it isn't accessible.

Does this make sense?

**Comment by jesings** [comment]
Duri how it works, so we can talk to him about it.ng our meeting yesterday, Brendan stressed that Lind, in general is not a server, and that besides one of the 2 current file tables, very little is persistent. He explained that the lind code didn't stay in memory and was only brought up when system calls were made. He wasn't quite sure how the file table persisted but @detectivelyw seemed to know
A buffer in microvisor was generally what we were thinking, but the exact way to have this buffer be referenced in the file table (and how to make it persistent) was somewhat confusing to us.

**Comment by JustinCappos** [comment]
I think unless you are doing named pipes (which we are not now) you need
not make it persistent.

I can explain the file system operations / setup for Lind (perhaps in
person, when I return?), but this shouldn't be needed to make in memory
pipes work.  You'll just need to know if your file descriptor goes to a
pipe or to the write / read handlers that do disk I/O.

**Comment by rennergade** [comment]
Thanks for the comments, there was some confusion on how the the repy side of Lind actually existed through the execution process. From testing it seems like implementing a system to hold the pipe data shouldn't be a problem, and we've whiteboarded out a way to do so.

However the issues in #10 that we've discovered are going to a pose a problem in determining which process is reading and writing, and most likely need to be fixed before pipe() is properly implemented.

**Comment by rennergade** [comment]
As an aside, we also talked about how Python strings are immutable, so the pipe should most likely be implemented as a Python list of "chars"

**Comment by rennergade** [comment]
1. In NaCl we need to have a pipe handler. It will basically call `open()` twice, set those fd’s in the `int fd[2]` array, and then send a new pipe RPC with the two fd’s.
2. In SafePOSIX, we’ll need to change the fdtable (now by cage) to also have the entry “pipe” which will tell what pipe to direct to.
3. We’ll need to add a dictionary of pipes by pipe number to `lind_fs_calls`. This will contain information such as the read and write locks, and data
4. The data will be stored as a list of “chars” to keep it mutable
5. Modify `read`/`write`/`close` to deal with if the fd is a pipe and if read or write.

**Comment by JustinCappos** [comment]
Why does NaCl need the pipe handler?  Why do we need actual fds?  Shouldn't
the ufds that are created be virtual ones (just entries in the ufd table)?

**Comment by rennergade** [comment]
So NaCl has handlers for all the syscalls [here](https://github.com/Lind-Project/native_client/blob/develop/src/trusted/service_runtime/nacl_syscall_common.c)

I believe since the pipe call gives us fds were still going to need NaCl fds as well as ufds, at least how were currently set up. 

I'm going to further investigate removing NaCl fds as in issue #18 , but this is the easier path for now.

**Comment by JustinCappos** [comment]
Is this only for real pipes (e.g., those known by the OS) or for upipes
that go between uprocesses?  I think the latter doesn't need NaCl fds.

**Comment by rennergade** [comment]
This is for implementing upipes to go between uprocesses. The pipes would only exist in repy-space - but to get information to and from the pipes ie `read()`/`write()` we'll still need nacl fd's so we can utilize the same system calls.

**Comment by JustinCappos** [comment]
I talked with @rennergade and I understand now that since NaCl translates the fds from each system call using its the NaCl system call table before passing them onto Repy, we need to either remove the NaCl table or have a way for Repy to add a fd.

**Comment by rennergade** [comment]
This is mostly complete however I'm still seeing the following problems:
1) The read error documented [here](https://github.com/Lind-Project/lind_project/issues/27). This is more of a global issue but obviously effects the correctness of pipe.
2) I'm seeing an ordering issue that I'm not sure if its a problem:
If I:

1. `printf` some message in parent
2. `write` a second message to the pipe
3. `read` that message from pipe in child, and then subesequently `write` it to STD_OUT

I see the write from the pipe from steps 2 + 3 printed before the `printf` from step 1. That's not the ordering I get when compiled normally through gcc.

**Comment by JustinCappos** [comment]
Odd.  I think the parent's write to STDOUT should have completed first so
long as you are calling flush(STDOUT).  Do you do this?

**Comment by rennergade** [comment]
`fflush(stdout)` does fix that behavior. POSIX says that newlines should automatically flush stdout, which isn't happening here. So I'll put that in a separate issue.

**Comment by rennergade** [comment]
These changes have been implemented and are now merged into develop.
